language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "${sonaruser}"
    token:
      secure: "${sonartoken}"
    branches:
      - master
      - develop
jdk:
    - oraclejdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'